function buildTestHarnesses()
%BUILDTESTHARNESSES Create the external Simulink Test harnesses (ADR-033).
%   One externally-saved harness per physical architecture model, used by
%   every simulation test case in GalacticSoupSystemTests.mldatx. The
%   harness makes the root interface explicitly observable: the CUT's
%   root inports (AmbientGravity, CustomerOrders, InboundSupplies - which
%   direct simulation silently grounded) become explicit Constant-0
%   sources, and the root outports become harness outports. The virtual
%   Telemetry bus flattens at the model-reference boundary into named
%   scalar outports (Telemetry_totalPower_kW, Telemetry_plantMode);
%   this generator names the feeding lines so yout carries the names
%   the test criteria harvest by.
%
%   Destructive and idempotent: existing harnesses are deleted and
%   recreated. Run before buildSystemTestFile after any root-interface
%   change.

proj = currentProject;
models = {'PhysicalHyperCook','HyperCookSystemHarness','HyperCook'; ...
          'PhysicalLeanBroth','LeanBrothSystemHarness','LeanBroth'; ...
          'PhysicalEverSimmer','EverSimmerSystemHarness','EverSimmer'};

% external harness files are created in the CURRENT FOLDER - work from
% each variant's folder (architecture/physical/<Variant>/) so the harness
% lands beside the model and *_harnessInfo.xml it belongs to
oldDir = pwd;
restoreDir = onCleanup(@() cd(oldDir));

for m = 1:size(models,1)
    mdl = models{m,1}; hn = models{m,2};
    cd(char(fullfile(proj.RootFolder, 'architecture', 'physical', models{m,3})));
    load_system(mdl);
    try
        sltest.harness.delete(mdl, hn);
    catch
    end
    sltest.harness.create(mdl, 'Name', hn, 'SaveExternally', true, ...
        'Source', 'Constant', 'Sink', 'Outport');
    sltest.harness.load(mdl, hn);
    set_param(hn, 'SaveOutput', 'on', 'SaveFormat', 'Dataset');
    addBowlsPerHourTap(hn);
    % name the outport feed lines so yout elements are harvestable by name
    % (this runs AFTER the bph tap so the new outport is named too)
    outs = find_system(hn, 'SearchDepth', 1, 'BlockType', 'Outport');
    for k = 1:numel(outs)
        [~, nm] = fileparts(outs{k});
        nm = get_param(outs{k}, 'Name');
        if startsWith(nm, 'Telemetry_')
            sig = extractAfter(nm, 'Telemetry_');
        else
            sig = nm;
        end
        ph = get_param(outs{k}, 'PortHandles');
        set_param(get_param(ph.Inport(1), 'Line'), 'Name', sig);
    end
    % the AmbientGravity source resolves from the SAME dictionary entry
    % that drives the gravity physics (ADR-034): one source of truth, and
    % a Gravity_g override moves the signal and the physics coherently
    % the port is bus-typed (GravityData): a bus-typed Constant takes a
    % struct expression matching the bus elements
    set_param([hn '/AmbientGravity'], 'Value', ...
        'struct(''gravity_g'', Gravity_g, ''compensation_pct'', 100)');
    save_system(hn);
    sltest.harness.close(mdl, hn);
    fprintf('%s: harness %s built (external)\n', mdl, hn);
end

% register harness files with the project
pf = {proj.Files.Path};
for m = 1:size(models,1)
    f = fullfile(char(proj.RootFolder), 'architecture', 'physical', ...
        models{m,3}, [models{m,2} '.slx']);
    if isfile(f) && ~any(strcmpi(pf, f)), addFile(proj, f); end
end
end

function addBowlsPerHourTap(hn)
%ADDBOWLSPERHOURTAP Expose packaged throughput in bowls/HOUR at the harness.
%   The models work in bowls/second (Simscape's time base, ADR-014) but
%   SR-GS-002 and every reported throughput figure are bowls/hour. Reading
%   the raw OutboundShipments.flow_bps signal against a bph requirement
%   means multiplying by 3600 in your head at exactly the moment you are
%   trying to decide whether a design passes.
%
%   This taps the bus feeding the OutboundShipments harness outport,
%   selects flow_bps, scales it, and lands it on a new outport,
%   OutboundShipments_bph - directly comparable to the requirement.
%
%   The tap is added at the HARNESS top level, deliberately: the Output
%   Conversion Subsystem beside it is generated by sltest.harness.create
%   and would lose any edit the next time the harness is rebuilt.
%
%   The signal is an INSTANTANEOUS rate. To average it over a window, use
%   a time-weighted integral - trapz(t,y)/(t(end)-t(1)) - not mean(y):
%   the solver is variable-step, so plain mean() weights densely-sampled
%   stretches too heavily. On HyperCook's steady window that difference
%   is 308.78 bph by mean() against the correct 308.37.
outBlk = [hn '/OutboundShipments'];
ph = get_param(outBlk, 'PortHandles');
srcPort = get_param(get_param(ph.Inport(1), 'Line'), 'SrcPortHandle');
outPos = get_param(outBlk, 'Position');
y = outPos(2) + 185;   % clear of the existing outport column

sel = add_block('simulink/Signal Routing/Bus Selector', [hn '/SoupFlowSelect'], ...
    'OutputSignals', 'flow_bps', 'Position', [outPos(1)-215 y-18 outPos(1)-210 y+22]);
gn = add_block('simulink/Math Operations/Gain', [hn '/BowlsPerHour'], ...
    'Gain', '3600', 'Position', [outPos(1)-150 y-13 outPos(1)-120 y+13]);
op = add_block('simulink/Sinks/Out1', [hn '/OutboundShipments_bph'], ...
    'Position', [outPos(1) y-8 outPos(3) y+8]);

add_line(hn, srcPort, get_param(sel, 'PortHandles').Inport(1));
add_line(hn, get_param(sel, 'PortHandles').Outport(1), ...
    get_param(gn, 'PortHandles').Inport(1));
add_line(hn, get_param(gn, 'PortHandles').Outport(1), ...
    get_param(op, 'PortHandles').Inport(1));
end
