function buildBehaviorTestFile(captureBaselines)
%BUILDBEHAVIORTESTFILE Build the behavioral component Simulink Test file.
%   buildBehaviorTestFile() recreates BehaviorComponentTests.mldatx using
%   the existing reviewed baseline files.
%
%   buildBehaviorTestFile(true) deliberately recaptures all 21 waveform
%   baselines from the current models before rebuilding the test file. Use
%   that form only after reviewing an intentional behavior change.

arguments
    captureBaselines (1,1) logical = false
end

proj = currentProject;
testDir = fullfile(char(proj.RootFolder), 'behavior', 'tests');
testFilePath = fullfile(testDir, 'BehaviorComponentTests.mldatx');
inputFilePath = fullfile(testDir, 'BehaviorComponentInputs.mat');
baselineDir = fullfile(testDir, 'baselines');

if ~isfolder(baselineDir)
    mkdir(baselineDir);
end

writeInputData(inputFilePath);
registerProjectFile(proj, inputFilePath, 'Design');

sltest.testmanager.clear;
sltest.testmanager.clearResults;
if isfile(testFilePath)
    removeProjectFileIfPresent(proj, testFilePath);
    delete(testFilePath);
end

tf = sltest.testmanager.TestFile(testFilePath);
defaultSuites = getTestSuites(tf);
cookLine = initializeSuite(defaultSuites(1), 'CookLine');
cookVat = initializeSuite(createTestSuite(tf, 'CookVat'), 'CookVat');
packager = initializeSuite(createTestSuite(tf, 'Packager'), 'Packager');
prepUnit = initializeSuite(createTestSuite(tf, 'PrepUnit'), 'PrepUnit');
qcStation = initializeSuite(createTestSuite(tf, 'QCStation'), 'QCStation');
storage = initializeSuite(createTestSuite(tf, 'Storage'), 'Storage');
supervisor = initializeSuite(createTestSuite(tf, 'Supervisor'), 'Supervisor');

% CookLine
tc = addCase(cookLine, 'baseline', 'fullLoadSteadyState', ...
    'BehCookLine', 2000, inputFilePath, 'CookLine_fullLoad', ...
    'Abundant supply reaches rated flow and full power after settling.');
setCriteria(tc, cookLineFullLoadCriteria());
configureBaseline(tc, proj, baselineDir, 'BehCookLine_fullLoad.mat', ...
    captureBaselines, { ...
    'outflow_bps', 90/3600*0.02, 0, 5, 'linear'; ...
    'power_kW', 1, 0, 5, 'linear'});

tc = addCase(cookLine, 'baseline', 'halfLoadSteadyState', ...
    'BehCookLine', 2000, inputFilePath, 'CookLine_quarterLoad', ...
    'Quarter-capacity supply settles to the expected load-scaled power.');
setCriteria(tc, cookLineQuarterLoadCriteria());
configureBaseline(tc, proj, baselineDir, 'BehCookLine_quarterLoad.mat', ...
    captureBaselines, { ...
    'outflow_bps', 90/3600*0.02, 0, 5, 'linear'; ...
    'power_kW', 1, 0, 5, 'linear'});

tc = addCase(cookLine, 'baseline', 'disabledLineIdles', ...
    'BehCookLine', 600, inputFilePath, 'CookLine_disabled', ...
    'A disabled line produces no flow and draws no power.');
setCriteria(tc, cookLineDisabledCriteria());
configureBaseline(tc, proj, baselineDir, 'BehCookLine_disabled.mat', ...
    captureBaselines, { ...
    'outflow_bps', 90/3600*0.02, 0, 5, 'linear'; ...
    'power_kW', 1, 0, 5, 'linear'});

% CookVat
tc = addCase(cookVat, 'baseline', 'referenceCycleWithDefaults', ...
    'BehCookVat', 5400, inputFilePath, 'CookVat_reference', ...
    'Three complete fill, heat, simmer, drain, and clean cycles.');
setCriteria(tc, cookVatReferenceCriteria());
configureBaseline(tc, proj, baselineDir, 'BehCookVat_reference.mat', ...
    captureBaselines, { ...
    'outflow_bps', 0.005, 0, 5, 'zoh'; ...
    'power_kW', 0.8, 0, 5, 'zoh'; ...
    'vatTemp_C', 1, 0, 5, 'linear'; ...
    'state', 0, 0, 5, 'zoh'; ...
    'hopperLevel_bowls', 1, 0, 5, 'linear'});

tc = addCase(cookVat, 'baseline', 'disabledVatStaysIdle', ...
    'BehCookVat', 1000, inputFilePath, 'CookVat_disabled', ...
    'A disabled vat remains idle with negligible flow and power.');
setCriteria(tc, cookVatDisabledCriteria());
configureBaseline(tc, proj, baselineDir, 'BehCookVat_disabled.mat', ...
    captureBaselines, { ...
    'outflow_bps', 0.005, 0, 5, 'zoh'; ...
    'power_kW', 0.8, 0, 5, 'zoh'; ...
    'vatTemp_C', 1, 0, 5, 'linear'; ...
    'state', 0, 0, 5, 'zoh'; ...
    'hopperLevel_bowls', 1, 0, 5, 'linear'});

% Packager
tc = addCase(packager, 'baseline', 'capacityLimitedSteadyState', ...
    'BehPackager', 900, inputFilePath, 'Packager_capacity', ...
    'Abundant supply saturates packaging at rated capacity.');
setCriteria(tc, packagerCapacityCriteria());
configureBaseline(tc, proj, baselineDir, 'BehPackager_capacity.mat', ...
    captureBaselines, {'outflow_bps', 200/3600*0.02, 0, 5, 'linear'});

tc = addCase(packager, 'baseline', 'supplyLimitedPassThrough', ...
    'BehPackager', 900, inputFilePath, 'Packager_supplyLimited', ...
    'Supply below capacity passes through at steady state.');
setCriteria(tc, packagerSupplyCriteria());
configureBaseline(tc, proj, baselineDir, ...
    'BehPackager_supplyLimited.mat', captureBaselines, ...
    {'outflow_bps', 200/3600*0.02, 0, 5, 'linear'});

tc = addCase(packager, 'baseline', 'disabledPackagerProducesNothing', ...
    'BehPackager', 400, inputFilePath, 'Packager_disabled', ...
    'A disabled packager produces no output.');
setCriteria(tc, packagerDisabledCriteria());
configureBaseline(tc, proj, baselineDir, 'BehPackager_disabled.mat', ...
    captureBaselines, {'outflow_bps', 200/3600*0.02, 0, 5, 'linear'});

% PrepUnit
tc = addCase(prepUnit, 'baseline', 'capacityLimitedSteadyState', ...
    'BehPrepUnit', 1200, inputFilePath, 'PrepUnit_capacity', ...
    'Abundant supply saturates preparation flow and demand at capacity.');
setCriteria(tc, prepCapacityCriteria());
configureBaseline(tc, proj, baselineDir, 'BehPrepUnit_capacity.mat', ...
    captureBaselines, { ...
    'outflow_bps', 100/3600*0.02, 0, 5, 'linear'; ...
    'demand_bps', 100/3600*0.02, 0, 5, 'linear'});

tc = addCase(prepUnit, 'baseline', 'supplyLimitedSteadyState', ...
    'BehPrepUnit', 1200, inputFilePath, 'PrepUnit_supplyLimited', ...
    'Supply below capacity passes through at steady state.');
setCriteria(tc, prepSupplyCriteria());
configureBaseline(tc, proj, baselineDir, ...
    'BehPrepUnit_supplyLimited.mat', captureBaselines, { ...
    'outflow_bps', 100/3600*0.02, 0, 5, 'linear'; ...
    'demand_bps', 100/3600*0.02, 0, 5, 'linear'});

tc = addCase(prepUnit, 'baseline', 'disabledUnitProducesNothing', ...
    'BehPrepUnit', 600, inputFilePath, 'PrepUnit_disabled', ...
    'A disabled preparation unit produces no output or demand.');
setCriteria(tc, prepDisabledCriteria());
configureBaseline(tc, proj, baselineDir, 'BehPrepUnit_disabled.mat', ...
    captureBaselines, { ...
    'outflow_bps', 100/3600*0.02, 0, 5, 'linear'; ...
    'demand_bps', 100/3600*0.02, 0, 5, 'linear'});

% QCStation
tc = addCase(qcStation, 'baseline', 'passRejectSplitRatio', ...
    'BehQCStation', 2000, inputFilePath, 'QC_split', ...
    'Inspection splits flow according to the configured reject fraction.');
addOverrides(tc, {'CalibPeriod_s', 1e6});
setCriteria(tc, qcSplitCriteria());
configureBaseline(tc, proj, baselineDir, 'BehQCStation_split.mat', ...
    captureBaselines, { ...
    'passflow_bps', 0.02*0.98*0.02, 0, 5, 'linear'; ...
    'rejectflow_bps', 0.02*0.02*0.02, 0, 5, 'linear'; ...
    'calibrating', 0, 0, 1, 'zoh'; ...
    'contamDetected_bps', 1e-9, 0, 5, 'linear'; ...
    'contamEscaped_bps', 1e-9, 0, 5, 'linear'});

tc = addCase(qcStation, 'baseline', 'calibrationOutageBlocksFlow', ...
    'BehQCStation', 800, inputFilePath, 'QC_calibration', ...
    'Calibration creates a visible outage in the pass stream.');
addOverrides(tc, {'CalibPeriod_s', 300, 'CalibTime_s', 100});
setCriteria(tc, qcCalibrationCriteria());
configureBaseline(tc, proj, baselineDir, ...
    'BehQCStation_calibration.mat', captureBaselines, { ...
    'passflow_bps', 0.02*0.98*0.02, 0, 5, 'linear'; ...
    'rejectflow_bps', 0.02*0.02*0.02, 0, 5, 'linear'; ...
    'calibrating', 0, 0, 1, 'zoh'; ...
    'contamDetected_bps', 1e-9, 0, 5, 'linear'; ...
    'contamEscaped_bps', 1e-9, 0, 5, 'linear'});

tc = addCase(qcStation, 'baseline', 'contaminationDetectionSplit', ...
    'BehQCStation', 2000, inputFilePath, 'QC_contamination', ...
    'Detected contamination moves from the pass stream to rejects.');
addOverrides(tc, {'CalibPeriod_s', 1e6, ...
    'ContamIncidence', 0.05, 'DetectSensitivity', 0.995});
setCriteria(tc, qcContaminationCriteria());
configureBaseline(tc, proj, baselineDir, ...
    'BehQCStation_contamination.mat', captureBaselines, { ...
    'passflow_bps', 0.02*0.98*0.02, 0, 5, 'linear'; ...
    'rejectflow_bps', 0.02*0.02*0.02, 0, 5, 'linear'; ...
    'calibrating', 0, 0, 1, 'zoh'; ...
    'contamDetected_bps', 2e-5, 0, 5, 'linear'; ...
    'contamEscaped_bps', 1e-7, 0, 5, 'linear'});

tc = addCase(qcStation, 'baseline', 'disabledStationBlocksFlow', ...
    'BehQCStation', 200, inputFilePath, 'QC_disabled', ...
    'A disabled QC station blocks the pass stream.');
setCriteria(tc, qcDisabledCriteria());
configureBaseline(tc, proj, baselineDir, 'BehQCStation_disabled.mat', ...
    captureBaselines, { ...
    'passflow_bps', 0.02*0.98*0.02, 0, 5, 'linear'; ...
    'rejectflow_bps', 0.02*0.02*0.02, 0, 5, 'linear'; ...
    'calibrating', 0, 0, 1, 'zoh'; ...
    'contamDetected_bps', 1e-9, 0, 5, 'linear'; ...
    'contamEscaped_bps', 1e-9, 0, 5, 'linear'});

% Storage
tc = addCase(storage, 'baseline', 'conservationOfMass', ...
    'BehStorage', 1000, inputFilePath, 'Storage_conservation', ...
    'Stored level follows the inflow-minus-draw mass balance.');
setCriteria(tc, storageConservationCriteria());
configureBaseline(tc, proj, baselineDir, 'BehStorage_conservation.mat', ...
    captureBaselines, { ...
    'outflow_bps', 0.005, 0, 5, 'linear'; ...
    'level_bowls', 6, 0, 5, 'linear'; ...
    'starved', 0, 0, 1, 'zoh'});

tc = addCase(storage, 'baseline', 'starvationDropsOutflow', ...
    'BehStorage', 200, inputFilePath, 'Storage_starvation', ...
    'A nearly empty store becomes starved and chokes output.');
addOverrides(tc, {'InitLevel_bowls', 1});
setCriteria(tc, storageStarvationCriteria());
configureBaseline(tc, proj, baselineDir, 'BehStorage_starvation.mat', ...
    captureBaselines, { ...
    'outflow_bps', 0.005, 0, 5, 'linear'; ...
    'level_bowls', 6, 0, 5, 'linear'; ...
    'starved', 0, 0, 1, 'zoh'});

tc = addCase(storage, 'baseline', 'capacityClamp', ...
    'BehStorage', 100, inputFilePath, 'Storage_capacity', ...
    'Storage level saturates at capacity without overshoot.');
addOverrides(tc, {'InitLevel_bowls', 990});
setCriteria(tc, storageCapacityCriteria());
configureBaseline(tc, proj, baselineDir, 'BehStorage_capacity.mat', ...
    captureBaselines, { ...
    'outflow_bps', 0.005, 0, 5, 'linear'; ...
    'level_bowls', 6, 0, 5, 'linear'; ...
    'starved', 0, 0, 1, 'zoh'});

% Supervisor
tc = addCase(supervisor, 'baseline', ...
    'modeSequenceFollowsHealthAndFlow', 'BehSupervisor', 300, ...
    inputFilePath, 'Supervisor_sequence', ...
    'Supervisor follows startup, running, degraded, and recovery phases.');
setCriteria(tc, supervisorSequenceCriteria());
configureBaseline(tc, proj, baselineDir, 'BehSupervisor_sequence.mat', ...
    captureBaselines, { ...
    'lineEnable', 0, 0, 0.01, 'zoh'; ...
    'plantMode', 0, 0, 0.01, 'zoh'});

tc = addCase(supervisor, 'baseline', 'lineEnableTracksHealth', ...
    'BehSupervisor', 300, inputFilePath, 'Supervisor_sequence', ...
    'Line 2 enable follows its health input through fault and recovery.');
setCriteria(tc, supervisorEnableCriteria());
configureBaseline(tc, proj, baselineDir, ...
    'BehSupervisor_lineEnable.mat', captureBaselines, { ...
    'lineEnable', 0, 0, 0.01, 'zoh'; ...
    'plantMode', 0, 0, 0.01, 'zoh'});

tc = addCase(supervisor, 'baseline', 'startupHoldsAllLinesEnabled', ...
    'BehSupervisor', 5, inputFilePath, 'Supervisor_startup', ...
    'Startup keeps every healthy line enabled before flow begins.');
setCriteria(tc, supervisorStartupCriteria());
configureBaseline(tc, proj, baselineDir, 'BehSupervisor_startup.mat', ...
    captureBaselines, { ...
    'lineEnable', 0, 0, 0.01, 'zoh'; ...
    'plantMode', 0, 0, 0.01, 'zoh'});

saveToFile(tf);
registerProjectFile(proj, testFilePath, 'Test');
registerProjectFile(proj, fullfile(testDir, 'buildBehaviorTestFile.m'), 'Design');
registerProjectFile(proj, fullfile(testDir, 'runBehTests.m'), 'Design');
registerProjectFile(proj, fullfile(testDir, 'updateBehaviorBaselines.m'), 'Design');

fprintf('%s built: 7 suites, 21 baseline cases\n', testFilePath);
end

function suite = initializeSuite(suite, name)
suite.Name = name;
suite.Tags = {'behavior'};
for stray = getTestCases(suite)
    remove(stray);
end
end

function tc = addCase(suite, testType, name, model, stopTime, ...
        inputFile, inputVariable, description)
tc = createTestCase(suite, testType, name);
tc.Tags = {'behavior'};
tc.Description = description;
setProperty(tc, ...
    'Model', model, ...
    'SimulationMode', 'Normal', ...
    'OverrideStopTime', true, ...
    'StopTime', stopTime, ...
    'OverrideModelOutputSettings', true, ...
    'SaveOutput', true, ...
    'SignalLogging', true, ...
    'PlotSignalAfterSimulation', true, ...
    'SaveBaselineRunInTestResult', true, ...
    'SaveInputRunInTestResult', true);

input = addInput(tc, inputFile, 'CreateIterations', false);
input.InputString = inputExpression(model, inputVariable);
end

function expression = inputExpression(model, variable)
if ~bdIsLoaded(model)
    load_system(model);
end
ports = find_system(model, 'SearchDepth', 1, 'BlockType', 'Inport');
numbers = cellfun(@str2double, get_param(ports, 'Port'));
[~, order] = sort(numbers);
names = string(get_param(ports(order), 'Name'));
parts = string(variable) + ".getElement('" + names + "')";
expression = char(strjoin(parts, ','));
end

function addOverrides(tc, values)
ps = addParameterSet(tc, 'Name', 'overrides');
for k = 1:2:numel(values)
    addParameterOverride(ps, values{k}, values{k+1});
end
end

function setCriteria(tc, callback)
criteria = getCustomCriteria(tc);
criteria.Enabled = true;
criteria.Callback = callback;
end

function configureBaseline(tc, proj, baselineDir, filename, capture, specs)
path = fullfile(baselineDir, filename);
if capture
    if isfile(path)
        removeProjectFileIfPresent(proj, path);
        delete(path);
    end
    baseline = captureBaselineCriteria(tc, path, false);
    registerProjectFile(proj, path, 'Design');
else
    assert(isfile(path), ['Missing native baseline %s. Run ' ...
        'updateBehaviorBaselines(true) once to capture it.'], path);
    baseline = addBaselineCriteria(tc, path);
    registerProjectFile(proj, path, 'Design');
end

signalCriteria = getSignalCriteria(baseline);
for k = 1:size(specs, 1)
    name = string(specs{k, 1});
    idx = find(endsWith(string({signalCriteria.BlockPath}), "/" + name), 1);
    assert(~isempty(idx), 'Baseline %s has no signal %s.', filename, name);
    signalCriteria(idx).Enabled = true;
    signalCriteria(idx).AbsTol = specs{k, 2};
    signalCriteria(idx).RelTol = specs{k, 3};
    signalCriteria(idx).LeadingTol = specs{k, 4};
    signalCriteria(idx).LaggingTol = specs{k, 4};
    signalCriteria(idx).InterpMethod = specs{k, 5};
end
end

function registerProjectFile(proj, path, label)
files = proj.Files;
idx = find(string({files.Path}) == string(path), 1);
if isempty(idx)
    relative = char(erase(string(path), string(proj.RootFolder) + filesep));
    projectFile = addFile(proj, relative);
else
    projectFile = files(idx);
end
labels = projectFile.Labels;
hasLabel = any(string({labels.CategoryName}) == "Classification" & ...
    string({labels.Name}) == string(label));
if ~hasLabel
    addLabel(projectFile, 'Classification', label);
end
end

function removeProjectFileIfPresent(proj, path)
files = proj.Files;
idx = find(string({files.Path}) == string(path), 1);
if ~isempty(idx)
    removeFile(proj, files(idx));
end
end

function writeInputData(path)
inputs = struct;

inputs.CookLine_fullLoad = scalarInputs( ...
    {'supply_bps','enable'}, [0;2000], [1 1;1 1]);
quarterSupply = 0.25 * 90 / 3600;
inputs.CookLine_quarterLoad = scalarInputs( ...
    {'supply_bps','enable'}, [0;2000], ...
    [quarterSupply 1;quarterSupply 1]);
inputs.CookLine_disabled = scalarInputs( ...
    {'supply_bps','enable'}, [0;600], [1 0;1 0]);

inputs.CookVat_reference = scalarInputs( ...
    {'supply_bps','enable'}, [0;5400], [0.5 1;0.5 1]);
inputs.CookVat_disabled = scalarInputs( ...
    {'supply_bps','enable'}, [0;1000], [0.5 0;0.5 0]);

inputs.Packager_capacity = scalarInputs( ...
    {'supply_bps','enable'}, [0;900], [1 1;1 1]);
inputs.Packager_supplyLimited = scalarInputs( ...
    {'supply_bps','enable'}, [0;900], [0.02 1;0.02 1]);
inputs.Packager_disabled = scalarInputs( ...
    {'supply_bps','enable'}, [0;400], [1 0;1 0]);

inputs.PrepUnit_capacity = scalarInputs( ...
    {'supply_bps','enable'}, [0;1200], [1 1;1 1]);
inputs.PrepUnit_supplyLimited = scalarInputs( ...
    {'supply_bps','enable'}, [0;1200], [0.01 1;0.01 1]);
inputs.PrepUnit_disabled = scalarInputs( ...
    {'supply_bps','enable'}, [0;600], [1 0;1 0]);

inputs.QC_split = scalarInputs( ...
    {'inflow_bps','enable'}, [0;2000], [0.02 1;0.02 1]);
inputs.QC_calibration = scalarInputs( ...
    {'inflow_bps','enable'}, [0;800], [0.02 1;0.02 1]);
inputs.QC_contamination = scalarInputs( ...
    {'inflow_bps','enable'}, [0;2000], [0.02 1;0.02 1]);
inputs.QC_disabled = scalarInputs( ...
    {'inflow_bps','enable'}, [0;200], [0.02 0;0.02 0]);

inputs.Storage_conservation = scalarInputs( ...
    {'inflow_bps','draw_bps'}, [0;1000], [0.2 0.1;0.2 0.1]);
inputs.Storage_starvation = scalarInputs( ...
    {'inflow_bps','draw_bps'}, [0;200], [0 0.5;0 0.5]);
inputs.Storage_capacity = scalarInputs( ...
    {'inflow_bps','draw_bps'}, [0;100], [1 0;1 0]);

t = [0;10;10.001;100;100.001;200;200.001;300];
health = [ ...
    1 1 1 1; 1 1 1 1; 1 1 1 1; 1 1 1 1; ...
    1 0 1 1; 1 0 1 1; 1 1 1 1; 1 1 1 1];
flow = [0;0;0.1;0.1;0.1;0.1;0.1;0.1];
inputs.Supervisor_sequence = vectorInputs( ...
    {'lineHealth','outFlow_bps'}, t, {health, flow});
inputs.Supervisor_startup = vectorInputs( ...
    {'lineHealth','outFlow_bps'}, [0;5], ...
    {ones(2,4), zeros(2,1)});

save(path, '-struct', 'inputs');
end

function ds = scalarInputs(names, time, data)
values = cell(1, numel(names));
for k = 1:numel(names)
    values{k} = data(:, k);
end
ds = vectorInputs(names, time, values);
end

function ds = vectorInputs(names, time, values)
ds = Simulink.SimulationData.Dataset;
for k = 1:numel(names)
    signal = timeseries(values{k}, time, 'Name', names{k});
    ds = ds.addElement(signal, names{k});
end
end

function callback = cookLineFullLoadCriteria()
callback = sprintf([ ...
    'y = test.sltest_simout.get(''yout'');\n' ...
    'outflow = y{1}.Values.Data; power = y{2}.Values.Data;\n' ...
    'test.verifyEqual(outflow(end), 90/3600, ''RelTol'', 0.02, ''rated flow'');\n' ...
    'test.verifyEqual(power(end), 50, ''RelTol'', 0.02, ''full power'');\n']);
end

function callback = cookLineQuarterLoadCriteria()
callback = sprintf([ ...
    'y = test.sltest_simout.get(''yout''); power = y{2}.Values.Data;\n' ...
    'test.verifyEqual(power(end), 18.5, ''RelTol'', 0.05, ''quarter-load power'');\n']);
end

function callback = cookLineDisabledCriteria()
callback = sprintf([ ...
    'y = test.sltest_simout.get(''yout'');\n' ...
    'test.verifyEqual(y{1}.Values.Data(end), 0, ''AbsTol'', 1e-6, ''zero flow'');\n' ...
    'test.verifyEqual(y{2}.Values.Data(end), 0, ''AbsTol'', 1e-6, ''zero power'');\n']);
end

function callback = cookVatReferenceCriteria()
callback = sprintf([ ...
    'y = test.sltest_simout.get(''yout'');\n' ...
    'flow = y{1}.Values; power = y{2}.Values; temp = y{3}.Values;\n' ...
    'state = y{4}.Values; hopper = y{5}.Values;\n' ...
    's = double(state.Data(:));\n' ...
    'test.verifyEqual(double(sort(unique(s)))'', 0:5, ''all states visited'');\n' ...
    'entered = (s(2:end)==4) & (s(1:end-1)~=4);\n' ...
    'test.verifyEqual(sum(entered), 3, ''three drain events'');\n' ...
    'test.verifyEqual(trapz(flow.Time,flow.Data),150,''AbsTol'',1,''total drained'');\n' ...
    'starts=find(s==4 & [true;s(1:end-1)~=4]);\n' ...
    'ends=find(s~=4 & [false;s(1:end-1)==4]);\n' ...
    'amounts=zeros(1,numel(starts));\n' ...
    'for k=1:numel(starts), a=max(1,starts(k)-1); b=ends(k); ' ...
        'amounts(k)=trapz(flow.Time(a:b),flow.Data(a:b)); end\n' ...
    'test.verifyEqual(amounts,repmat(50,1,3),''AbsTol'',1,''one batch per drain'');\n' ...
    'test.verifyGreaterThanOrEqual(max(temp.Data),94,''temperature peak lower bound'');\n' ...
    'test.verifyLessThanOrEqual(max(temp.Data),99,''temperature peak upper bound'');\n' ...
    'test.verifyLessThan(min(temp.Data(temp.Time>100)),20,''post-warmup cooling'');\n' ...
    'test.verifyEqual(max(power.Data),40,''RelTol'',0.02,''peak power'');\n' ...
    'test.verifyGreaterThanOrEqual(min(hopper.Data),0,''nonnegative hopper'');\n' ...
    'sf=interp1(state.Time,s,flow.Time,''previous'',''extrap'');\n' ...
    'test.verifyEqual(flow.Data(sf~=4),zeros(nnz(sf~=4),1),''AbsTol'',1e-9,''flow only in Drain'');\n' ...
    'changed=s([true;diff(s)~=0]); pairs=[changed(1:end-1) changed(2:end)];\n' ...
    'allowed=[0 1;1 2;2 3;3 4;4 5;5 1];\n' ...
    'test.verifyTrue(all(ismember(pairs,allowed,''rows'')),''legal state sequence'');\n']);
end

function callback = cookVatDisabledCriteria()
callback = sprintf([ ...
    'y = test.sltest_simout.get(''yout''); flow=y{1}.Values;\n' ...
    'power=y{2}.Values.Data; state=y{4}.Values.Data;\n' ...
    'test.verifyEqual(double(unique(state)),0,''Idle state'');\n' ...
    'test.verifyLessThan(trapz(flow.Time,flow.Data),0.1,''negligible flow'');\n' ...
    'test.verifyEqual(mean(power),0,''AbsTol'',1e-6,''zero mean power'');\n']);
end

function callback = packagerCapacityCriteria()
callback = endValueCriteria(1, 200/3600, 'RelTol', 0.02, 'rated flow');
end

function callback = packagerSupplyCriteria()
callback = endValueCriteria(1, 0.02, 'RelTol', 0.02, 'supply pass-through');
end

function callback = packagerDisabledCriteria()
callback = endValueCriteria(1, 0, 'AbsTol', 1e-6, 'zero flow');
end

function callback = prepCapacityCriteria()
callback = sprintf([ ...
    'y=test.sltest_simout.get(''yout'');\n' ...
    'test.verifyEqual(y{1}.Values.Data(end),100/3600,''RelTol'',0.02,''rated flow'');\n' ...
    'test.verifyEqual(y{2}.Values.Data(end),100/3600,''RelTol'',0.02,''rated demand'');\n']);
end

function callback = prepSupplyCriteria()
callback = endValueCriteria(1, 0.01, 'RelTol', 0.02, 'supply pass-through');
end

function callback = prepDisabledCriteria()
callback = sprintf([ ...
    'y=test.sltest_simout.get(''yout'');\n' ...
    'test.verifyEqual(y{1}.Values.Data(end),0,''AbsTol'',1e-6,''zero flow'');\n' ...
    'test.verifyEqual(y{2}.Values.Data(end),0,''AbsTol'',1e-9,''zero demand'');\n']);
end

function callback = qcSplitCriteria()
callback = sprintf([ ...
    'y=test.sltest_simout.get(''yout''); pass=y{1}.Values; reject=y{2}.Values.Data;\n' ...
    'sel=pass.Time>=1500; p=mean(pass.Data(sel)); r=mean(reject(sel));\n' ...
    'test.verifyEqual(p/(p+r),0.98,''RelTol'',0.01,''pass/reject ratio'');\n' ...
    'test.verifyEqual(p+r,0.02,''RelTol'',0.02,''mass conservation'');\n']);
end

function callback = qcCalibrationCriteria()
callback = sprintf([ ...
    'y=test.sltest_simout.get(''yout''); pass=y{1}.Values; calib=y{3}.Values.Data;\n' ...
    'test.verifyEqual(max(calib),1,''AbsTol'',1e-9,''calibration entered'');\n' ...
    'sel=pass.Time>=310 & pass.Time<=390;\n' ...
    'test.verifyLessThan(mean(pass.Data(sel)),0.1*0.02*0.98,''outage flow'');\n']);
end

function callback = qcContaminationCriteria()
callback = sprintf([ ...
    'y=test.sltest_simout.get(''yout''); pass=y{1}.Values; reject=y{2}.Values.Data;\n' ...
    'det=y{4}.Values.Data; esc=y{5}.Values.Data; sel=pass.Time>=1500;\n' ...
    'p=mean(pass.Data(sel)); r=mean(reject(sel)); d=mean(det(sel)); e=mean(esc(sel));\n' ...
    'passQ=0.02*0.98; contam=passQ*0.05;\n' ...
    'test.verifyEqual(d,contam*0.995,''RelTol'',0.01,''detected split'');\n' ...
    'test.verifyEqual(e,contam*0.005,''RelTol'',0.01,''escaped split'');\n' ...
    'test.verifyEqual(d/(d+e),0.995,''RelTol'',1e-6,''sensitivity exact'');\n' ...
    'test.verifyEqual(p,passQ-d,''RelTol'',0.01,''pass loses detected'');\n' ...
    'test.verifyEqual(r,0.02*0.02+d,''RelTol'',0.01,''reject gains detected'');\n' ...
    'test.verifyEqual(p+r,0.02,''RelTol'',0.02,''mass conservation'');\n']);
end

function callback = qcDisabledCriteria()
callback = endValueCriteria(1, 0, 'AbsTol', 1e-6, 'zero pass flow');
end

function callback = storageConservationCriteria()
callback = sprintf([ ...
    'y=test.sltest_simout.get(''yout''); out=y{1}.Values.Data; level=y{2}.Values.Data;\n' ...
    'test.verifyEqual(level(end),600,''RelTol'',0.01,''mass balance'');\n' ...
    'test.verifyEqual(mean(out(end-5:end)),0.1,''RelTol'',0.05,''draw tracking'');\n']);
end

function callback = storageStarvationCriteria()
callback = sprintf([ ...
    'y=test.sltest_simout.get(''yout''); out=y{1}.Values; level=y{2}.Values.Data; starved=y{3}.Values.Data;\n' ...
    'test.verifyLessThan(level(end),0.5,''near-empty level'');\n' ...
    'test.verifyEqual(starved(end),1,''AbsTol'',1e-9,''starved flag'');\n' ...
    'sel=out.Time>=100; test.verifyLessThan(mean(out.Data(sel)),0.05,''choked output'');\n']);
end

function callback = storageCapacityCriteria()
callback = sprintf([ ...
    'y=test.sltest_simout.get(''yout''); level=y{2}.Values.Data;\n' ...
    'test.verifyEqual(level(end),1000,''RelTol'',0.005,''capacity reached'');\n' ...
    'test.verifyLessThanOrEqual(max(level),1000+1e-6,''no overshoot'');\n']);
end

function callback = supervisorSequenceCriteria()
callback = sprintf([ ...
    'y=test.sltest_simout.get(''yout''); mode=y{2}.Values;\n' ...
    'm=double(mode.Data); t=mode.Time;\n' ...
    'test.verifyEqual(m(find(t<10,1,''last'')),0,''startup mode'');\n' ...
    'test.verifyEqual(m(find(t>=10 & t<100,1,''last'')),1,''running mode'');\n' ...
    'test.verifyEqual(m(find(t>=100 & t<200,1,''last'')),2,''degraded mode'');\n' ...
    'test.verifyEqual(m(end),1,''recovered mode'');\n']);
end

function callback = supervisorEnableCriteria()
callback = sprintf([ ...
    'y=test.sltest_simout.get(''yout''); enable=y{1}.Values; line2=enable.Data(:,2); t=enable.Time;\n' ...
    'test.verifyEqual(line2(find(t>=150 & t<200,1,''last'')),0,''AbsTol'',1e-9,''disabled while unhealthy'');\n' ...
    'test.verifyEqual(line2(find(t>=250,1,''last'')),1,''AbsTol'',1e-9,''enabled after recovery'');\n']);
end

function callback = supervisorStartupCriteria()
callback = sprintf([ ...
    'y=test.sltest_simout.get(''yout'');\n' ...
    'test.verifyEqual(double(y{2}.Values.Data(end)),0,''startup mode'');\n' ...
    'test.verifyEqual(y{1}.Values.Data(end,:),ones(1,4),''AbsTol'',1e-9,''all lines enabled'');\n']);
end

function callback = endValueCriteria(outputIndex, expected, toleranceName, tolerance, message)
callback = sprintf([ ...
    'y=test.sltest_simout.get(''yout'');\n' ...
    'test.verifyEqual(y{%d}.Values.Data(end),%.17g,''%s'',%.17g,''%s'');\n'], ...
    outputIndex, expected, toleranceName, tolerance, message);
end
